### ISSUE TITLE
Add support for es6 modules

### ISSUE THREAD

**Issue by benogle** [anvilco/node-anvil#309]

**Comment by newhouse** [comment]
This ticket really turned out to be about not dynamically importing/requiring files by reading from the file system, and the trouble that causes for bundlers:
https://app.hubspot.com/live-messages/9465393/inbox/4784147334#comment

> We've run into an issue with the anvil nodejs sdk.  @anvilco/anvil.  Specifically src/graphql/mutations/index.js and src/graphql/queries/index.js use runtime logic to calculate require() calls.  This breaks bundlers (we're using esbuild) as they don't know about those files to inline them.  I'm working on a manual patch for the anvil SDK now to import these statically, but it'd be nice to not have to maintain that patch.
