### ISSUE TITLE
Unable to import Anvil 3.0 from ESM module

### ISSUE THREAD

**Issue by jekh** [anvilco/node-anvil#354]
It looks like the 3.0 release does not play nicely when imported from ESM modules. An extra layer of `default` is added. This affects both regular ESM `import` statements and dynamic import, which is shown below. This appears to be a regression since 2.x.

### 3.0.0
```
Welcome to Node.js v18.16.0.
Type ".help" for more information.
> await import("@anvilco/anvil")
[Module: null prototype] {
  __esModule: true,
  default: {
    default: [class Anvil] {
      UploadWithOptions: [class UploadWithOptions],
      VERSION_LATEST: -1,
      VERSION_LATEST_PUBLISHED: -2
    }
  }
}
> 
```

### 2.15.1
```
elcome to Node.js v18.16.0.
Type ".help" for more information.
> await import("@anvilco/anvil")
[Module: null prototype] {
  default: [class Anvil] {
    UploadWithOptions: [class UploadWithOptions],
    VERSION_LATEST: -1,
    VERSION_LATEST_PUBLISHED: -2
  }
}
> 
```

The last lines of `dist/index.js` are:
```js
Anvil.VERSION_LATEST_PUBLISHED = VERSION_LATEST_PUBLISHED;var _default =

Anvil;exports.default = _default;
```

It looks like the Anvil class export is being transpiled into an ESM-ish default export, but [Node exposes module.exports as a default export](https://nodejs.org/docs/latest-v18.x/api/esm.html#import-statements) already when importing into an ESM context, resulting in a "double default".

**Comment by jekh** [comment]
Thanks, the beta worked!
```
> await import("@anvilco/anvil")
[Module: null prototype] {
  default: <ref *1> [class Anvil] {
    UploadWithOptions: [class UploadWithOptions],
    VERSION_LATEST: -1,
    VERSION_LATEST_PUBLISHED: -2,
    default: [Circular *1]
  }
}
```

I suspect CJS also wasn't working correctly due to the default export. It also appears to be fixed as well :heavy_check_mark: 
```
> require("@anvilco/anvil")
<ref *1> [class Anvil] {
  UploadWithOptions: [class UploadWithOptions],
  VERSION_LATEST: -1,
  VERSION_LATEST_PUBLISHED: -2,
  default: [Circular *1]
}
```

**Comment by newhouse** [comment]
@jekh This is now out in `3.0.1`.

**Comment by jekh** [comment]
It appears to be working great! Thanks for the quick fix on this one.
