### ISSUE TITLE
Error types are inaccurate

### ISSUE THREAD

**Issue by knowlesc** [anvilco/node-anvil#476]
the `GraphQLResponse` type is defined like this:
![image](https://github.com/user-attachments/assets/5493876b-307f-4e87-be60-367935639c7c)

However, if there's an internal node error, which we occasionally see ("Premature close"), the response looks like this:
```
{
      data: undefined,
      errors: [
        {
          name: "FetchError",
          message: "Invalid response body while trying to fetch https://app.useanvil.com/graphql: Premature close",
          code: "ERR_STREAM_PREMATURE_CLOSE",
          stack:
            "FetchError: Invalid response body while trying to fetch https://app.useanvil.com/graphql: Premature close",
        },
      ],
      statusCode: 200
    }
```

It would be great if we could rely on the error types to be able to safely parse errors.

Thank you!

**Comment by newhouse** [comment]
OK, that sounds good. I added this in `3.3.1`.  @knowlesc can you pull that down and try it?

**Comment by newhouse** [comment]
Going to close this for now.
